### PR TITLE
Revert "Added Automatic download of youtube.apk file"

### PR DESCRIPTION
**Pull request by thomas930**
Reverts Jarvis-Ank/Re-Vanced#20

This version of "Re-Vanced.ipynb" cannot work properly, REVERT to previous version is recommended. 

1. When I choose"Automatic" Mode, it will download the latest Youtube APK from apkmirror.com.  MANY warnings appear when compiling because of using too updated youtube APK. It seems the "revanced-patches" cannot bump patches compatibility to latest Youtube APK as soon as possible. It will need sometimes for "revanced-patches" contributors manually bump patches compatibility to latest Youtube APK. 
```
WARNING: Skipping swipe-controls, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.24.34, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping downloads, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.27.39, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping seekbar-tapping, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hide-create-button, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hide-shorts-button, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping return-youtube-dislike, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hide-autoplay-button, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping disable-fullscreen-panels, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping old-quality-layout, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hide-watermark, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping sponsorblock, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.22.36, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping enable-wide-searchbar, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping tablet-mini-player, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.26.35, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping disable-auto-captions, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping minimized-playback, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping custom-video-buffer, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping always-autorepeat, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping microg-support, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping custom-playback-speed, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.24.34, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hdr-auto-brightness, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping remember-video-quality, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.22.36, 17.24.35, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping video-ads, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.14.35, 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping general-ads, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35, 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
WARNING: Skipping hide-infocard-suggestions, reason: incompatible with version 17.36.39. This patch is only compatible with version com.google.android.youtube: 17.25.34, 17.26.35, 17.27.39, 17.28.34, 17.29.34, 17.32.35, 17.33.42, 17.36.37 
```

2. When I choose "Google Drive" or "Manual" Mode, the following error (Undefined Variable) was printed. 
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-1-2e281a8df3d2>](https://localhost:8080/#) in <module>
    200   exec('pip install gdown')
    201 #Zulu JDK-17 download and install
--> 202 msg(f'[{depencies}/{depencies}] Zulu JDK-17')
    203 exec('wget -O ./ReVanced/zulu-jdk17.deb https://cdn.azul.com/zulu/bin/zulu17.34.19-ca-jdk17.0.3-linux_amd64.deb')
    204 exec('sudo apt install ./ReVanced/zulu-jdk17.deb')

NameError: name 'depencies' is not defined
```

### CODE REVIEW

**Comment by Bartek20** [comment]
I'll have a look at it when I get home.
1. Soon I will start working on the selection of the Application version for download.
2. It looks like a small error in the code, but I am not able to verify it now.

**Comment by Antonino200217** [comment]
Issue 2 fixed in #22

**Comment by thomas930** [comment]
> Issue 2 fixed in #22

This is to confirm Issue 2 fixed, Issue 1 i still fixing.
Thanks so much for fixing.

**Comment by thomas930** [comment]
Any updates on fixing issue 1?
If it needs time to fix it, I suggest to disable / remove the "Automatic" Mode temporarily.

**Comment by Bartek20** [comment]
Adding this functionality should not take long, because the script already creates a list of available versions, but currently I do not have much time to analyze the code in this direction due to school and the need to catch up after a week of absence.

To facilitate the work at this time, I will make a small change in the code that will change the default working mode to 'Google Drive' and add an annotation about current problems.

**Comment by Bartek20** [comment]
Changed in #24

**Comment by thomas930** [comment]
Thanks so much!
That's Good!

**Comment by Jarvis-Ank** [comment]
I'll check it out, i think bartek is busy now.

Aswin N Kaimal

**Pull request closed without merging**
