### PR TITLE
GUI, New features, Code refactorization, DEV Tools

### PR DESCRIPTION
**Pull request by Bartek20**
- [x] Added User friendly GUI.
- [x] Changed script output to show the progress of work.
- [x] Added custom version selection.
- [x] Added support for latest MicroG version.
- [x] Added support for Google Drive link instead of id.
- [x] Refactorized code.

- [x] Added DEV Tools section:
* GUI generator (after generating, you have to manually edit and upload the new version to Github)
* Github API Rate Limit Checker

It seems that automatic download of youtube.apk from apkmirror and apkpure databases is not possible due to **_cloudflare_** security. If anyone has a solution to this problem, feel free to share your solutions.

### CODE REVIEW

**Comment by Jarvis-Ank** [comment]
> * [x]  Added User friendly GUI.
> * [x]  Changed script output to show the progress of work.
> * [x]  Added custom version selection.
> * [x]  Added support for latest MicroG version.
> * [x]  Added support for Google Drive link instead of id.
> * [x]  Refactorized code.
> * [x]  Added DEV Tools section:
> 
> * GUI generator (after generating, you have to manually edit and upload the new version to Github)
> * Github API Rate Limit Checker
> 
> It seems that automatic download of youtube.apk from apkmirror and apkpure databases is not possible due to **_cloudflare_** security. If anyone has a solution to this problem, feel free to share your solutions.

I'll check it when i have time. I'm a bit busy now.. if you wish to add new features you could make a new branch and work on that in the meantime.

**Comment by Bartek20** [comment]
@Jarvis-Ank sorry for tagging, but are you still planning to work on this repository or do i need to create pull requests anymore since you won't merge them anyway?

**Comment by Jarvis-Ank** [comment]
Hey I've been busy lately. I'll merge it, i not able to check all the code.
Are you sure it's working ? Then let me know I'll merge it. Also can you
maintain the repo ?.

Aswin N Kaimal

**Comment by Bartek20** [comment]
I checked the code and if the correct link to the youtube.apk file from the google disk was given, the program works without any complaints in the event of errors (there should be no errors) I am currently working on a system for saving full logs to a file that the user will be able to attach to the report in order to be able to repeat the entire situation while fixing the code.
What do you mean by maintain repo? You mean fixing bugs and merging the fixes by myself?

**Comment by Jarvis-Ank** [comment]
Yes, that's right.

Aswin N Kaimal

**Comment by Bartek20** [comment]
Then I can maintain the repo.

**Comment by Jarvis-Ank** [comment]
Sounds good. Is your account private i can't find you in the add
collaborators tab

Aswin N Kaimal

**Comment by Bartek20** [comment]
From what I can see in the settings, the option to hide the account is unchecked

**Comment by Bartek20** [comment]
I was able to join as a collaborator but still can't merge my pull request because I need a review that I can't give myself.

**Comment by Jarvis-Ank** [comment]
I'll do it

Aswin N Kaimal

**Review by Jarvis-Ank — APPROVED** [review]
Update to files -> @Bartek20

**Pull request merged**
